services:
  youtube_converter:
    build:
      context: .
    restart: unless-stopped
    container_name: youtube_converter
    networks:
      - traefik
    expose:
      - "8000"
    volumes:
      - ./app:/home/app
networks:
  traefik:
    external: true