services:
  yt-downloader:
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: yt
    ports:
      - ${APP_PORT}:8000
    volumes:
      - ${APP}:/home/app
    restart: unless-stopped