services:
  yt_converter:
    build:
      context: .
    container_name: yt_converter
    restart: always
    networks:
      - proxy
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.youtube.rule=Host(`yt.test`)"
      - "traefik.http.routers.youtube.entrypoints=websecure"
      - "traefik.http.routers.youtube.tls=true"
      - "traefik.http.services.youtube.loadbalancer.server.port=8000"
    volumes:
      - ./app:/home/app

networks:
  proxy:
    external: true
