services:
  python:
    build:
      context: .
    restart: unless-stopped
    networks:
      - proxy
    expose:
      - "80"
    volumes:
      - ./app:/home/app
networks:
  proxy:
    external: true